# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1efbc1341b938656042789430a5b8ca80d5661d82573bc8e7044b78f21d9565eea391c5c66a68477fdd3f3cd150a8781a782f00abdc401a994bfda5bebd52d5a

test:
  secret_key_base: d9a2d0bb5045c4c6a1452e6542cf2aa0f84b4480c79297a090812c268ca2f23df97524be60cc420d70260a5f730a0c93cde0daabd6ff8b29c2c9a8b3d2539cc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
